baseURL = 'https://restonisourhome.org/'
languageCode = 'en-us'
title = 'Reston Is Our Home'
theme = 'starter'

SectionPagesMenu = "main"

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 10

[markup.goldmark.renderer]
unsafe= true