baseURL = 'https://www.restonisourhome.org/'
languageCode = 'en-us'
title = 'Reston Is Our Home'
theme = 'hero-banner'

SectionPagesMenu = "main"

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 10
    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"
        weight = 20

[markup.goldmark.renderer]
unsafe = true